services:
  - type: web
    name: licoreria-front
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false # Se configura manualmente con la URL del backend, ej: https://licoreria-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
